#pragma once
#include <string>

bool BoolExp();
bool BoolExp2();
bool LogExp();
bool LogExp2();
bool CmpExp();
bool CmpAndOperand();
bool CmpOp();
bool Operand();
bool Operators();
bool Operators2();
bool Operator();
bool ArithExp();
bool ArithExp1();
bool ArithExp2();
bool ArithExp3();
bool ArithExp4();